### ISSUE TITLE
大哥呀，我hosts里面保存了其他文件都给我干掉了

### ISSUE THREAD

**Issue by MfNiu** [tinycedar/lily#4]
大哥呀，我hosts里面保存了其他内容都给我干掉了吗，泪奔中

**Comment by tinycedar** [comment]
Sorry, 我 应该备份下的

**Comment by MfNiu** [comment]
哈哈，能否追加呢

**Comment by tinycedar** [comment]
@MfNiu 修改hosts配置吗？  右边直接修改即可，自动保存

**Comment by MfNiu** [comment]
发现好像我的想法应该是错的，我的意思是你的软件新增hosts记录的时候通过追加方式 不是通过清空重写

**Comment by tinycedar** [comment]
@MfNiu 这样hosts会越来越长，显得比较乱。

**Comment by MfNiu** [comment]
嗯嗯，是的，我的想法不对
