### ISSUE TITLE
请问你在说明里所提到支持的浏览器是怎么使用的？

### ISSUE THREAD

**Issue by fy138** [tinycedar/lily#6]
如果使用这些支持的浏览器？
webview 组件吗？

**Comment by tinycedar** [comment]
Lily的核心功能是双击切换hosts后立即生效；但在一些浏览器下做不到，所以我经过测试列了下支持立即生效的浏览器名单

**Comment by eddy8** [comment]
github上什么时候可以release一个新的windows版本？

**Comment by tinycedar** [comment]
@eddy8 最新版已经发布，请移步[Releases](https://github.com/tinycedar/lily/releases)下载
